# HTTP Server
server:
  port: 8889

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jmsanchezmartagon/config-server
          default-label: main
          clone-on-start: true